### ISSUE TITLE
License for usage as a library?

### ISSUE THREAD

**Issue by pombredanne** [app-sre/sretoolbox#37]
Hi, 
I was wondering if you may consider using a license that would help reusing your fine code as a library in Apache-licensed code that I co-maintain at https://github.com/nexB/container-inspector and https://github.com/nexB/scancode-toolkit and https://github.com/nexB/scancode.io/
Something like an LGPL or an Apache license would work better than a GPL for library usage.

Thank you for you kind consideration!

**Comment by apahim** [comment]
We should use Apache License 2.0 indeed. This one went unoticed. Fixed.

**Comment by pombredanne** [comment]
@apahim Thank you ++ for the swift reply and action! :bow:
