### ISSUE TITLE
License of retry decorator

### ISSUE THREAD

**Issue by pombredanne** [app-sre/sretoolbox#40]
While reviewing the code of https://github.com/app-sre/sretoolbox/blob/c0def7de7bd176995d2de8c4fcdaa8ed8c2d3b6d/sretoolbox/utils/retry.py#L12 I visited the URL at https://www.calazan.com/retry-decorator-for-python-3/  and found that it was mentioning this:

> Below is a nice retry decorator I found on this https://www.saltycrane.com/blog/2009/11/trying-out-retry-decorator-python/ site. I just changed one line of code to make it Python 3 compatible (basically had to change the print statement to a function).
 

And on https://www.saltycrane.com/blog/2009/11/trying-out-retry-decorator-python/

> Code / License
> This code is also on github at: https://github.com/saltycrane/retry-decorator  It is BSD licensed. 

And a link to https://github.com/saltycrane/retry-decorator/blob/master/LICENSE

This is a BSD-3-Clause. It would make sense to add this in the repo?

**Comment by apahim** [comment]
Good catch. I will look into it.

**Comment by apahim** [comment]
New version 0.13.1 contains all changes to licensing:

https://pypi.org/project/sretoolbox/0.13.1/

Thank you!
